const achievementDefinitions = [
        { key: "first_quiz", title: "Erster Schritt", desc: "Absolviere dein allererstes Quiz." },
        { key: "streak_5", title: "Zenturio-In-Ausbildung", desc: "Erreiche einen Streak von 5 richtigen Antworten." },
        { key: "streak_10", title: "Unaufhaltsam", desc: "Erreiche einen Streak von 10 richtigen Antworten." },
        { key: "streak_15", title: "Imperator-Modus", desc: "Erreiche einen Streak von 15 richtigen Antworten." },
        { key: "perfect_1", title: "Fehlerfrei Lvl 1", desc: "Schließe ein Lvl-1-Quiz mit einer glatten Note 1 ab." },
        { key: "perfect_2", title: "Fehlerfrei Lvl 2", desc: "Schließe ein Lvl-2-Quiz mit einer glatten Note 1 ab." },
        { key: "perfect_3", title: "Fehlerfrei Lvl 3", desc: "Schließe ein Lvl-3-Quiz mit einer glatten Note 1 ab." },
        { key: "perfect_4", title: "Fehlerfrei Lvl 4", desc: "Schließe ein Lvl-4-Quiz mit einer glatten Note 1 ab." },
        { key: "perfect_5", title: "Latein-Gott (Lvl 5)", desc: "Schließe ein Lvl-5-Quiz mit einer glatten Note 1 ab." },
        { key: "no_joker_lvl5", title: "Grammatik-Genie", desc: "Schließe Lvl 5 ohne Joker ab (Note 2 oder besser)." },
        { key: "speedy", title: "Blitzdenker", desc: "Beende ein Quiz mit ≥ 5 Fragen in unter 1 Minute." },
        { key: "vault_clean", title: "Kammerjäger", desc: "Starte ein Problem-Tresor-Training." },
        { key: "all_lessons", title: "Großinquisitor", desc: "Wähle alle Lektionen gleichzeitig für ein Quiz aus." },
        { key: "night_owl", title: "Nachtschicht", desc: "Lerne zu später Stunde (zwischen 22:00 und 05:00 Uhr)." },
        { key: "lucky_last", title: "Knappes Höschen", desc: "Beende eine Runde mit unter 5 Sekunden Restzeit." },
        { key: "grade_1_plus", title: "Senats-Präsident", desc: "Erziele die Bestnote 1+ in irgendeinem Quiz." },
        { key: "grade_2", title: "Solider Patrizier", desc: "Erreiche die Note 2 oder besser." },
        { key: "mode_lat_de", title: "Rom-Versteher", desc: "Beende ein Quiz im Modus 'Lat ➔ DE'." },
        { key: "mode_de_lat", title: "Ciceros Erbe", desc: "Beende ein Quiz im Modus 'DE ➔ Lat'." },
        { key: "mode_random", title: "Meister des Chaos", desc: "Beende ein Quiz im Abfragemodus 'Zufall'." },
        { key: "no_hints_win", title: "Ohne Spickzettel", desc: "Gewinne ein Quiz (Note ≤ 3) ohne eine einzige Eselsbrücke." },
        { key: "ten_times_quiz", title: "Dauerlerner", desc: "Absolviere insgesamt 10 Quiz-Runden auf diesem Gerät." },
        { key: "early_bird", title: "Frühaufsteher", desc: "Lerne am frühen Morgen zwischen 05:00 und 08:00 Uhr." },
        { key: "half_century", title: "Punktesammler", desc: "Erreiche in einer einzigen Runde über 50 Punkte." },
        { key: "hundred_club", title: "Punkte-Milliardär", desc: "Erreiche in einer einzigen Runde über 100 Punkte." },
        { key: "quick_skip", title: "Ehrliche Haut", desc: "Nutze den 'Weiß ich nicht'-Button in einer Runde." },
        { key: "joker_user", title: "Schummel-Ass", desc: "Setze erfolgreich einen Grammatik-Joker ein." },
        { key: "vault_downloaded", title: "Datensicherer", desc: "Lade deine Problem-Vokabeln als Backup-Datei herunter." },
        { key: "high_score_entry", title: "Ruhmeshalle", desc: "Trage dich in die Top-5-Verlaufsliste ein." },
        { key: "salve_master", title: "Höflicher Gruß", desc: "Beantworte die Vokabel 'salve' fehlerfrei." },
        { key: "roma_master", title: "Alle Wege nach Rom", desc: "Beantworte die Vokabel 'roma' fehlerfrei." },
        { key: "perfect_streak_3", title: "Triple-Sieg", desc: "Erreiche 3 perfekte Antworten nacheinander." },
        { key: "streak_20", title: "Göttlicher Lauf", desc: "Erreiche einen unglaublichen Streak von 20 richtigen Antworten." },
        { key: "streak_25", title: "Unsterblich", desc: "Erreiche einen beispiellosen Streak von 25 richtigen Antworten." },
        { key: "run_20", title: "Eiserner Fleiß", desc: "Schließe insgesamt 20 Runden auf diesem Gerät ab." },
        { key: "run_50", title: "Großmeister der Antike", desc: "Schließe insgesamt 50 Runden auf diesem Gerät ab." },
        { key: "vault_visit", title: "Tresorbauer", desc: "Betrete die neue Raumübersicht des Problem-Tresors." },
        { key: "no_hints_lvl4", title: "Freihändig durch Lvl 4", desc: "Beende Level 4 ohne jegliche Eselsbrücken mit Note ≤ 2." },
        { key: "no_hints_lvl5", title: "Titanenhirn", desc: "Schließe Level 5 komplett ohne Hilfen und ohne Tipps ab." },
        { key: "lunch_break", title: "Mittagssnack", desc: "Lerne fleißig in der Mittagszeit zwischen 12:00 und 14:00 Uhr." },
        { key: "after_school", title: "Hausaufgaben erledigt", desc: "Mache ein Quiz am Nachmittag zwischen 14:00 und 17:00 Uhr." },
        { key: "prime_time", title: "Abendglorie", desc: "Absolviere ein erfolgreiches Training zwischen 18:00 und 21:00 Uhr." },
        { key: "double_one", title: "Doppel-Zenturio", desc: "Habe mindestens zwei Einträge mit Note 1 im Verlauf." },
        { key: "triple_one", title: "Triumphator", desc: "Sichere dir dreimal die Note 1 in deinen Top-Runden." },
        { key: "full_history", title: "Historiker", desc: "Fülle deine Verlaufsliste mit 5 vollen Runden aus." },
        { key: "salve_roma", title: "Römischer Bürger", desc: "Beantworte sowohl 'salve' als auch 'roma' in einer Session richtig." },
        { key: "level_1_master", title: "Grundausbildung", desc: "Absolviere 5 Runden exklusiv auf Level 1." },
        { key: "level_2_master", title: "Legionär", desc: "Absolviere 5 Runden exklusiv auf Level 2." },
        { key: "level_3_master", title: "Prätorianer", desc: "Absolviere 5 Runden exklusiv auf Level 3." },
        { key: "level_4_master", title: "Feldherr", desc: "Absolviere 5 Runden exklusiv auf Level 4." },
        { key: "level_5_master", title: "Olymp-Aufsteiger", desc: "Absolviere 5 Runden exklusiv auf Level 5." },
        { key: "all_modes", title: "Allrounder", desc: "Spiele mindestens einmal jeden der 3 Abfragemodi." },
        { key: "speed_120", title: "Schallgeschwindigkeit", desc: "Beende ein Quiz in unter 2 Minuten." },
        { key: "score_150", title: "Punktemonster", desc: "Sammle mehr als 150 Punkte in einer Runde." },
        { key: "score_200", title: "Unantastbarer Highscore", desc: "Erreiche epische 200+ Punkte in einem Durchlauf." },
        { key: "skip_three", title: "Taktischer Rückzug", desc: "Nutze den 'Weiß ich nicht'-Button dreimal in einer Runde." },
        { key: "joker_double", title: "Joker-Zwilling", desc: "Setze zwei Grammatik-Joker in einer einzigen Runde ein." },
        { key: "clean_sheet", title: "Weiße Weste", desc: "Löse ein Quiz mit mindestens 10 Fragen ganz ohne Fehler." },
        { key: "survivor", title: "Überlebenskünstler", desc: "Rette dich mit einer Note 4 ins Ziel." },
        { key: "comeback", title: "Phönix aus der Asche", desc: "Erreiche nach einer Note 5 oder 6 in der Folgerunde eine Note 1." },
        { key: "dark_learner", title: "Schattenritter", desc: "Absolviere ein komplettes Quiz im Dark-Mode." },
        { key: "light_learner", title: "Lichtbringer", desc: "Absolviere ein komplettes Quiz im Light-Mode." },
        { key: "perfect_vault", title: "Tresor gesprengt", desc: "Leere im Tresor-Modus mindestens eine Vokabel erfolgreich heraus." },
        { key: "completionist", title: "Ultra-Legende", desc: "Schalte die Hälfte aller verfügbaren Trophäen frei." }
    ];